// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:3288a199-de19-4c92-924f-3b9170a765ca',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'tronwallet-hosting-mobilehub-854809954',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dqrnkm14kxhmf.cloudfront.net',
    'aws_mobile_analytics_app_id': 'b9744f8cb1934d4eaf1b56b3b2395423',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3cf6ba24-e73f-48f5-aca4-85cb7d962561',
    'aws_project_name': 'TronWallet',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'tronwallet-mobilehub-854809954',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_i3fDuXSwH',
    'aws_user_pools_web_client_id': '5g1p7qhf73s6p569gselt67su9',
}

export default awsmobile;
