# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tronwallet2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  # Pods for tronwallet2
  pod "RNTron", :path => "../node_modules/react-native-tron/ios/"

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'


  pod "react-native-camera", 
    :path => "../node_modules/react-native-camera"


  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'



  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
  
end
